openapi: 3.0.0
info:
  title: Outbox RPC API
  version: 1.0.0
servers:
- url: /
paths:
  /api/indexer/lastFinalizedBlock:
    get:
      operationId: lastFinalizedBlock
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lastFinalizedBlock_200_response'
          description: Successful operation
      summary: Get the last finalized block
      x-eov-operation-handler: controllers/DefaultController
  /api/indexer/merkleTree/{blockNumber}:
    get:
      operationId: merkleTreeByBlockNumber
      parameters:
      - description: Block number to retrieve the MerkleTree
        explode: false
        in: path
        name: blockNumber
        required: true
        schema:
          example: 5
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/merkleTreeByBlockNumber_200_response'
          description: Successful operation
      summary: Get the MerkleTree that was in the OutboxUtxo at the given blockNumber
      x-eov-operation-handler: controllers/DefaultController
  /api/indexer/messages/{fromBlock}/{toBlock}:
    get:
      operationId: messagesByBlockRange
      parameters:
      - description: Start block number
        explode: false
        in: path
        name: fromBlock
        required: true
        schema:
          example: 0
          type: integer
        style: simple
      - description: End block number
        explode: false
        in: path
        name: toBlock
        required: true
        schema:
          example: 10
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messagesByBlockRange_200_response'
          description: Successful operation
      summary: Get messages from fromBlock to toBlock
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    messagesByBlockRange_200_response:
      example:
        messages:
        - block: 3
          message:
            destinationDomain: 0xCA
            sender: 0x0000000000000000000000000000000000000CA1
            recipient: 0x0000000000000000000000000000000000000EA1
            body: 0xADA
            version: 0
            nonce: 0
            originDomain: 0xEF
        - block: 3
          message:
            destinationDomain: 0xCA
            sender: 0x0000000000000000000000000000000000000CA1
            recipient: 0x0000000000000000000000000000000000000EA1
            body: 0xADA
            version: 0
            nonce: 0
            originDomain: 0xEF
      properties:
        messages:
          items:
            $ref: '#/components/schemas/messagesByBlockRange_200_response_messages_inner'
          type: array
      required:
      - messages
      type: object
    messagesByBlockRange_200_response_messages_inner:
      example:
        block: 3
        message:
          destinationDomain: 0xCA
          sender: 0x0000000000000000000000000000000000000CA1
          recipient: 0x0000000000000000000000000000000000000EA1
          body: 0xADA
          version: 0
          nonce: 0
          originDomain: 0xEF
      properties:
        block:
          example: 3
          type: integer
        message:
          $ref: '#/components/schemas/messagesByBlockRange_200_response_messages_inner_message'
      required:
      - block
      - message
      type: object
    merkleTreeByBlockNumber_200_response:
      example:
        merkleTree:
          count: 1
          branches:
          - 0x3b3153b5b2c1c50efca4b92a3804a037ceb79769545f8f4f85dec3bdbbaa7df5
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
        blockNumber: 5
      properties:
        blockNumber:
          example: 5
          type: integer
        merkleTree:
          $ref: '#/components/schemas/merkleTreeByBlockNumber_200_response_merkleTree'
      required:
      - blockNumber
      - merkleTree
      type: object
    messagesByBlockRange_200_response_messages_inner_message:
      example:
        destinationDomain: 0xCA
        sender: 0x0000000000000000000000000000000000000CA1
        recipient: 0x0000000000000000000000000000000000000EA1
        body: 0xADA
        version: 0
        nonce: 0
        originDomain: 0xEF
      properties:
        version:
          example: 0
          type: integer
        nonce:
          example: 0
          type: integer
        originDomain:
          example: 0xEF
          type: string
        sender:
          example: 0x0000000000000000000000000000000000000CA1
          type: string
        destinationDomain:
          example: 0xCA
          type: string
        recipient:
          example: 0x0000000000000000000000000000000000000EA1
          type: string
        body:
          example: 0xADA
          type: string
      required:
      - body
      - destinationDomain
      - nonce
      - originDomain
      - recipient
      - sender
      - version
      type: object
    merkleTreeByBlockNumber_200_response_merkleTree:
      example:
        count: 1
        branches:
        - 0x3b3153b5b2c1c50efca4b92a3804a037ceb79769545f8f4f85dec3bdbbaa7df5
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
        - 0x0000000000000000000000000000000000000000000000000000000000000000
      maxItems: 32
      minItems: 32
      properties:
        count:
          example: 1
          type: integer
        branches:
          example:
          - 0x3b3153b5b2c1c50efca4b92a3804a037ceb79769545f8f4f85dec3bdbbaa7df5
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          - 0x0000000000000000000000000000000000000000000000000000000000000000
          items:
            type: string
          type: array
      required:
      - branches
      - count
      type: object
    lastFinalizedBlock_200_response:
      example:
        lastFinalizedBlock: 10
      properties:
        lastFinalizedBlock:
          example: 10
          type: integer
      type: object
